{{- if .Values.checklist.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "checklist.serviceAccountName" . }}
  labels:
    {{- include "checklist.labels" . | nindent 4 }}
  {{- with .Values.checklist.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
