{{- if .Values.resource.node_port.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ "node-port-" }}{{ include "resource.fullname" . }}
  labels:
  {{- include "resource.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.resource.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.resource.node_port.nodePort }}
  selector:
  {{- include "resource.selectorLabels" . | nindent 4 }}
{{- end }}
