{{- if .Values.resource.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.serviceAccountName" . }}
  labels:
    {{- include "resource.labels" . | nindent 4 }}
  {{- with .Values.resource.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
