{{- if .Values.auth.node_port.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ "node-port-" }}{{ include "auth.fullname" . }}
  labels:
  {{- include "auth.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.auth.node_port.nodePort }}
  selector:
  {{- include "auth.selectorLabels" . | nindent 4 }}
{{- end }}
