{{- if .Values.progress.node_port.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ "node-port-" }}{{ include "progress.fullname" . }}
  labels:
  {{- include "progress.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.progress.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.progress.node_port.nodePort }}
  selector:
  {{- include "progress.selectorLabels" . | nindent 4 }}
{{- end }}
