{{- if .Values.progress.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "progress.serviceAccountName" . }}
  labels:
    {{- include "progress.labels" . | nindent 4 }}
  {{- with .Values.progress.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
