{{- if .Values.progress.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "progress.fullname" . }}
  labels:
    {{- include "progress.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "progress.fullname" . }}
  minReplicas: {{ .Values.progress.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.progress.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.progress.autoscaling.targetCPUUtilizationPercentage }}
    - type: User
      user:
        name: cpu
        targetAverageUtilization: {{ .Values.progress.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.progress.autoscaling.targetMemoryUtilizationPercentage }}
    - type: User
      user:
        name: memory
        targetAverageUtilization: {{ .Values.progress.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
