name: push-charts

on:
  push:
    branches:
      - dev
      - main

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.5.0
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/vote-app

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: push to ghcr
    steps:
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4
        with:
          useOCIRegistry: true
          registry-url: https://ghcr.io/${{ github.repository }}
          username: ${{ github.repository_owner }}
          access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          force: true
          chart-folder: charts/auth
